### ISSUE TITLE
Error while trying to getDataFromTree TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by umakantp** [jackyef/react-isomorphic-data#54]
I get the following error in the console log when I run my server:

```
Error while trying to getDataFromTree TypeError: Object(...) is not a function
    at _callee$ (webpack:///./server/src/utils/serverUtils.js?:68:97)
    at tryCatch (/Users/username/codex/myprojects/bunch/current/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/username/codex/myprojects/bunch/current/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (/Users/username/codex/myprojects/bunch/current/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at asyncGeneratorStep (webpack:///./server/src/utils/serverUtils.js?:18:103)
    at _next (webpack:///./server/src/utils/serverUtils.js?:20:194)
    at eval (webpack:///./server/src/utils/serverUtils.js?:20:364)

```

I was following the example given here to https://react-isomorphic-data.netlify.app/docs/ssr/getdatafromtree implement in my project.

If I change my project to use this: https://react-isomorphic-data.netlify.app/docs/ssr/rendertostringwithdata it works perfectly fine.

My packages:-
"react": "16.13.1"
"react-dom": "16.13.1"
"react-helmet": "6.0.0"
"react-isomorphic-data": "0.16.0"
"express": "4.17.1"
"isomorphic-fetch": "2.2.1"
"react-redux": "7.2.0"
"redux": "4.0.5"
"redux-thunk": "2.3.0"

Since renderToStringWithData is working fine and I'm fine using it, but I thought I'll report just in case you would want to take a look and fix it at why getDataFromTree not working.

My implementation was something like this.

```
export const reactRender = async (req, res) => {
   const {routes, store} = res.locals
   const dataClient = createDataClient({
     initialCache: {},
     ssr: true,
     headers: {
        'cookie': req.header('cookie'),
        'User-Agent': req.header('User-Agent'),
        'X-Forwarded-For': req.header('X-Forwarded-For'),
        'X-Real-IP': req.header('X-Real-IP'),
        'Accept': req.header('Accept'),
        'Host': req.header('Host')
     }
  })

  const tree = (
    <DataProvider client={dataClient}>
      <Provider store={store}>
         <AppContext.Provider
            value={context}>
            <StaticRouter location={req.url}>
               {routes}
             </StaticRouter>
         </AppContext.Provider>
      </Provider>
    </DataProvider>
  )

  let html
  try {
     await getDataFromTree(tree, dataClient)
     html = renderToString(tree)
  } catch (err) {
     console.error('Error while trying to getDataFromTree', err)
  }

  Object.assign(res.locals, {
     cache: dataClient.cache,
     appHtml: html
  })
}
```

I call this function in my index.js in express server as follows:

```
await reactRender(req, res)
res.set('Content-Type', 'text/html')
res.status(200).end(lodashTpl(res.locals))
```

Let me know if you need any other information from my side. Thanks.

**Comment by jackyef** [comment]
That's interesting, thank you for reporting! 

Could you help providing a simple reproduction so I can look more into it?
